apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: http
  annotations:
    description: "An application with a provider and component built for extending wasmCloud with custom capabilities"
    wasmcloud.dev/authors: wasmCloud team
    wasmcloud.dev/source-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/golang/providers/custom-template/wadm.yaml
    wasmcloud.dev/readme-md-url: https://github.com/wasmCloud/wasmCloud/blob/main/examples/golang/providers/custom-template/README.md
    wasmcloud.dev/homepage: https://github.com/wasmCloud/wasmCloud/tree/main/examples/golang/providers/custom-template
    wasmcloud.dev/categories: |
      capability-provider,provider,template,http-server,tinygo,golang,example
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: http-provider
      type: capability
      properties:
        image: file://./build/http-server.par.gz
      traits:
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
